variables:
  APPLICATION_NAME: face-recognition-fastapi-front
  DOCKER_IMAGE: ${DOCKER_HUB_USERNAME}/${APPLICATION_NAME}
  K8S_INGRESS_HOST: faces.home.maximemoreillon.com

image: moreillon/ci-dind
services:
  - name: docker:19.03.12-dind

build:
  stage: build
  tags:
    - dind
  script:
    # Docker hub login
    - echo "${DOCKER_HUB_PASSWORD}" | docker login --username ${DOCKER_HUB_USERNAME} --password-stdin
    # Building the container image
    - docker build -t ${DOCKER_IMAGE} .
    # Pushing the image to the registry
    - docker push ${DOCKER_IMAGE}

deploy:
  stage: deploy
  tags:
    - dind
  script:
    - envsubst < kubernetes_manifest.yml | kubectl apply -f -
    - kubectl rollout restart deployment/${APPLICATION_NAME}
  environment:
    name: production
    kubernetes:
      namespace: ${KUBERNETES_NAMESPACE}
