variables:
  APPLICATION_NAME: face-recognition-fastapi-front
  DOCKER_IMAGE: ${DOCKER_HUB_USERNAME}/${APPLICATION_NAME}

image: moreillon/ci-dind
services:
  - name: docker:24.0.7-dind

build:
  stage: build
  tags:
    - dind
  script:
    # Docker hub login
    - echo "${DOCKER_HUB_PASSWORD}" | docker login --username ${DOCKER_HUB_USERNAME} --password-stdin
    # Building the container image
    - docker build -t ${DOCKER_IMAGE} .
    # Pushing the image to the registry
    - docker push ${DOCKER_IMAGE}
