apiVersion: apps/v1
kind: Deployment
metadata:
  name: ${APPLICATION_NAME}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ${APPLICATION_NAME}
  template:
    metadata:
      labels:
        app: ${APPLICATION_NAME}
    spec:
      containers:
      - name: ${APPLICATION_NAME}
        image: ${DOCKER_IMAGE}
        # Ensures that k8s pulls a new image on restart
        imagePullPolicy: Always
        ports:
        - containerPort: 80
        envFrom:
        - secretRef:
           name: environment-variables
        env:
        - name: VUE_APP_API_URL
          value: /proxy/api
        - name: PROXY_API
          value: http://192.168.1.3:30020/
---
apiVersion: v1
kind: Service
metadata:
  name: ${APPLICATION_NAME}
spec:
  type: NodePort
  selector:
    app: ${APPLICATION_NAME}
  ports:
  - port: 80
    nodePort: ${NODEPORT}
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: ${APPLICATION_NAME}
  annotations:
    kubernetes.io/ingress.class: "nginx"
    cert-manager.io/cluster-issuer: "letsencrypt-prod" # This is necessary, no idea why
spec:
  tls:
  - hosts:
    - ${K8S_INGRESS_HOST}
    secretName: ${APPLICATION_NAME}
  rules:
  - host: ${K8S_INGRESS_HOST}
    http:
      paths:
      - path: /
        backend:
          serviceName: ${K8S_INGRESS_HOST}
          servicePort: 80
